spring:
  application:
    name: payroll-management-system

#Mongodb connection
  data:
    mongodb:
      uri: "${MONGODB_URI}"
      database: "${DB}"

#Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,beans

#Jwt security
jwt:
  secret: "${JWT_SECRET}"
  user:
    name: ${JWT_NAME}
    password: "${JWT_PASSWORD}"
  token:
    validity: 10800 #3hours